### PR TITLE
burning wounds

### PR DESCRIPTION
**Pull request by Tomcat-SG**
for now it adds the burning wounds permanent. Settings and all languages are missing and need to be added before merging into dev-tomcat

### CODE REVIEW

**Comment by Tomcat-SG** [comment]
a own model for the sterile bandage would be nice. atm we use the model of quicklot.

**Comment by FluffyGhoster** [comment]
I'm not sure what's the focus of this, we should perhalps clarify:

1. What kind of burns do we want to simulate
2. How do we simulate them (more specifically, what we consider to trigger the condition?)
3. What effect does it have on the unit/player?
4. How is it treated?

**Comment by Tomcat-SG** [comment]
@EvilItalianK
1. Ive added 4 different sizes of burning wound. Normal, small Medium and large.
2. Backblast, shell, grenade, burn, explosiv, burn and ropeburn are the types of damage which can trigger burning wounds if the unit get per selection damage more than 0.15
3. Atm small bleeding of 0.05 an pain
4. You can Bandage the wound with the sterile gauze

**Comment by FluffyGhoster** [comment]
@Tomcat-SG Shouldn't we also use https://community.bistudio.com/wiki/isBurning?

**Comment by Tomcat-SG** [comment]
> 
> 
> @Tomcat-SG Shouldn't we also use https://community.bistudio.com/wiki/isBurning?

@EvilItalianK Nah, i dont think so, because ace is defining it as unknown damage, so we only need to check the unknown damage as well. Done in my last Commit :)

**Comment by Tomcat-SG** [comment]
Outdated. This feature will be added in the future, but with a lot more content and based on the new ace damage system

**Pull request closed without merging**
