### PR TITLE
Pharma - Add action to place IO device with lidocaine to reduce IO placement pain

### PR DESCRIPTION
**Pull request by pool011**
**When merged this pull request will:**
- Add an action that administers lidocaine and places an IO device so that IO device placement pain is mitigated.

### IMPORTANT

- [Development Guidelines](https://ace3.acemod.org/wiki/development/) are read, understood and applied.
- Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.

### CODE REVIEW

**Comment by pool011** [comment]
Making this a draft because I need to update the string table

**Comment by MissHeda** [comment]
Did you test if it even works?
From looking at code it should not.

**Comment by pool011** [comment]
I haven't yet as I am in the middle of a move, hence the draft. But I am looking for feedback as well for how to do this best since this is my first time contributing to the system. If it is possible to administer the lidocaine before the IO is placed that is what makes the most sense to me so that we do not have to mess with in the IV placement function. If that is not possible I will have to tweak the IV placement function. But like I said I still need to test this and am not expecting this to be merge ready yet.

**Comment by pool011** [comment]
Haven't yet as I am in the middle of a move hence the draft. But I am looking for feedback as well as how to do this best since this is my first time contributing to the system. If it is possible to administer the lidocaine before the IO is placed that is what makes the most sense to me so that we do not have to mess with in the IV placement function. If that is not possible I will have to tweak the IV placement function. But like I said I still need to test this and am not expecting this to be merge ready yet.

**Comment by pool011** [comment]
I'm going to close this since it is non-functional and I have a lot of work to do on it

**Comment by pool011** [comment]
I'm going to close this since it is non-functional and I have a lot of work to do on it

**Pull request closed without merging**
