### PR TITLE
hemtt and sqfc

### PR DESCRIPTION
**Pull request by YonVclaw**
# Code Clean up
Cleaned code to comply with:
- sqf_validator.py
- config_validator.py
- config_style_checker.py

# Configured hemtt
- added PBOPREFIX files
- added the cba and ace includes to /includes

# Workflow
This currently one completes tests on a pull request, some parts are mission to build with sqfc currently.

# SQFC
Currently SQFC can only be compiled on a windows machine.

so here is how you do it!

1. Clone the repo locally
2. Configure the P: drive using the setup.py in tools
3. Install hemtt  https://github.com/BrettMayson/HEMTT/releases
4. Download ArmaScriptCompiler https://github.com/dedmen/ArmaScriptCompiler/actions
5. Copy the contents of ArmaScriptCompiler to the root folder of KAT
6. Run  ``hemtt build --release``
7. SQFC will be included in the release in the /releases folder

# Version number
I had no idea what the corect version number should be so, hemtt pulls the version from ```addons/main/script_version.hpp ```

### CODE REVIEW

**Comment by YonVclaw** [comment]
https://discord.com/channels/528955370941579265/540672510975279159/900651762715865119

a version of the hemtt exe that supports sqfc

**Comment by YonVclaw** [comment]
[@kat_hemtt_sqfc_branch2.6.0.8.zip](https://github.com/Tomcat-SG/KAM/files/7436230/%40kat_hemtt_sqfc_branch2.6.0.8.zip)
now with the correct file

**Review by byjokese — COMMENTED** [review]
Thanks for the work!  Did a quick test and the compiled result seem to be good.
One question, you added a submodule reference at .hemtt/template, but there's not _.gitmodules_ file to setup the URL. Was that on purpose?

**Comment by YonVclaw** [comment]
it was an oversite,
But I uploaded the gitmodules

**Comment by Slatery** [comment]
Would it be possible to clean up this PR to only the relevant parts? All the conflicts are caused by the changed indent characters in 99% of the files

**Comment by Slatery** [comment]
ah, I see why it's causing conflicts, it just needs to be brought up to current branches, since there were a few PRs merged since this one that touch the files you've touched here. shouldn't be too much of a headache

**Comment by YonVclaw** [comment]
done,

**Comment by YonVclaw** [comment]
@Slatery  the github work flow I have in the branch is that ok, or should I remove it

**Pull request closed without merging**
