### PR TITLE
Battlekeeper blood draw + other small things

### PR DESCRIPTION
**Pull request by YetheSamartaka**
- adds Battlekeeper blood draw feature with small adjustments(Static blood via SteamID **not** included).

- solved the blood group for the AI(Blood group is randomly assigned when someone checks AI dog tag or want to draw blood).

- fixed list of items in config.cpp.

-  added setting to disable beep and charge sound for AED/AED-X. Sounds will be enabled in default.

- changed default medical level requiered for AED and AED-X to lower level. It can be changed in the settings.

### CODE REVIEW

**Comment by Tomcat-SG** [comment]
Changes were mentioned in the DEV Discord Group. If they were done, then it can be merged!

**Comment by Tomcat-SG** [comment]
German translations will be pushed by myself.
The rest LGTM.

**Comment by redthirten** [comment]
Hi, sorry to comment on a merged commit, but I have a question regarding its added content. Out of curiosity, is there any particular reason why the static blood via SteamID was not included?

Our unit enjoys this functionality with the original mod from Battlekeeper (and would love to see it incorporated into this mod as part of the supposed merger), but we're trying to decide if we should keep using the original mod in tandem (and hope it doesn't conflict) or stop using the original mod (and give up the functionality).

**Comment by YetheSamartaka** [comment]
Hi. I was unsuccessful implementing it in proper manner. Maybe in the future, I will try to do so.

**Comment by redthirten** [comment]
> Hi. I was unsuccessful implementing it in proper manner. Maybe in the future, I will try to do so.

So I tried looking myself on how it would be implemented, and other than some formatting cleanup and proper incorporation into Circulation's CfgFunctions, I don't really think there would be much of an issue. The only issue I can see is that it would override/ignore the CBA Addon Option for blood type. A possible solution for this is to just change expected behavior by adding a description to the setting stating that it only applies for single player. However, if you wanted to present a choice and allow multiplayer to be either static or random, an additional checkbox setting would have to be added and called within the staticblood script (which also wouldn't be too hard). But all in all, I can understand if you feel this isn't the _cleanest_ possible way to do it, to which I would understand why you would be looking for a better way.

However, if you like this idea, I can try to whip it up and submit a PR with the additions :)

**Pull request merged**
