### PR TITLE
German Language Refinement for ChemWarfare

### PR DESCRIPTION
**Pull request by OverlordZorn**
German Language Refinement

Also: Is it "Toxic Gas" or "Mustard Gas" - it seems it was used interchangable.

### CODE REVIEW

**Comment by AtrixZockt** [comment]
It's mustard gas, i just forgot to update the name one i last updated it

**Comment by OverlordZorn** [comment]
> It's mustard gas, i just forgot to update the name one i last updated it

adapted my PR accordingly :)
(+ the german guide)

**Comment by OverlordZorn** [comment]
another question

grafik


Are the TripwireGas different from the ToxicGas items or are they the same cathegory?

**Review by AtrixZockt — APPROVED** [review]

**Comment by MiszczuZPolski** [comment]
LGTM

**Pull request merged**
