### PR TITLE
Hemopneumothorax

### PR DESCRIPTION
**Pull request by Conrimaceogain**
**When merged this pull request will:**

- Adds hemopneumothorax

Hemopneumothorax occurs as a configurable percentage chance when a patient first suffers from pneumothorax or when they are treated for pneumothorax. Treatment requires the use of the ARS Needle Decompression Kit. If the condition is left untreated, the patient's SP02 will drop slowly overtime.

An extra set of eyes on the few translations that were made and the missing translations would be great!

### CODE REVIEW

**Comment by Katskan** [comment]
Needle decompression won't do anything to a hemopneumothorax, ARS quite literally stands for air release system, it's neither positioned right or big enough for preventing blood from causing pulmonary/cardiac tamponade. A separate item/kit which would be used for hemopneumothorax or hemothorax would be a chest tube, alternatively a finger thoracotomy could be performed. Both procedures would likely require tools contained in a surgical kit item (scalpel and sutures)

**Comment by FluffyGhoster** [comment]
I think the kit to perform a tracheotomy can be used to perform an emergency hemopneumothorax as it already contains a scalpel and a tube, also the simple scalpel cut would be able to perform a decompression to a certain degree given the difference in pressure, thought it would not do it fully, probably also a sharpened enough knife could be used in case of emergency

Let me know if you'd like me to draw a logic flow for this part

**Comment by Katskan** [comment]
Yeah it'd be easy to make an "advanced airway kit" which contains all the bits and bobs needed for cric, endotracheal intubation and chest tubes. The only minor terminology thing is while tracheotomies can be done in emergencies usually they aren't, rather a cricothyroidotomy is performed. Usually people like anesthesiologists are best able to do trachs, whereas emergency medicine folk go for the cric, it's safer and easier to do on someone with minimal or even no sedation, and isn't right next to major central blood vessels which can be hit due to either unfamiliarity of internal anatomy or patient movement

**Comment by FluffyGhoster** [comment]
Yeah we can make an advanced airway kit but my question would be if the standard one would work for this case anyways since it contains a scalpel and we can use the 18g tube to drain the blood from the hemopneumothorax, so we don't have to add another object in the mod

**Comment by Katskan** [comment]
An 18g catheter? Large tubes like chest tubes are either measured in mm diameter or in fr. An 18g (1.27mm) is like an extreme last resort for an air-only decompression, but they're known to have high chance of failure after a short period. Usually you need a 16g(1.63mm) or 14g(1.83mm) needle. A typical chest tube size is like a 30fr tube (10mm) and an endotracheal tube usually ranges from 6.5mm to 7.5mm.

**Comment by FluffyGhoster** [comment]
Sorry let me correct that, I mean using the same needle used for emergency cricothyroidotomy to drain the hemothorax, however the presence of a hemothorax would not be the primary concern as the space inside the chest would accomodate enough fluid to cause an hemmoragic shock in the vast majority of patients (https://medictests.com/units/pneumothorax-and-hemothorax).

Sure it's a last resort and will probably also need sucking, a 14g needle seems like the safe smallest, maybe we can reuse the intubation tubes as emergency drains tho?

**Comment by Katskan** [comment]
So a smaller needle gauge number is a bigger needle, whereas a smaller french gauge is a smaller tube. A 14g needle is significantly larger than an 18g needle.

That said, it would make sense in an "advanced airway kit" to have a selection of appropriately sized chest tubes, ET tubes, decompression needles all together, and the scalpel and suture tools would be in the surgical kit

**Comment by Conrimaceogain** [comment]
I'm definitely a fan of the "advanced airway kit" idea, it's something more general that could be leveraged instead of requiring medics to add one thousand and one different little things to their kits. We could also leverage it as a required item for other advanced airway treatments.

**Comment by FluffyGhoster** [comment]
My question would be if we want to separate items tho?

eg, if you only have the scalpel, you can only do a manual drain, if you have a scalpel and a small tube you'll have to stay there and continue to clear the tube from coths as they would obstruct the flow (smaller = more likely it gets blocked), if you have a needle you'll have to suck it to drain the blood, etc.

So instead of having a kit, you get the tools you need and based on what you get you can or can't do certain things (no scalpel? you can't use the tube but only the needle, no tube? you have to either use the needle or the scalpel with manual draining, etc.), though a kit is easier to implement in the short term I fear that as we add more and more conditions the treatment kits will grow overtime to the point where you have many kits that contain the same set of things but only work on specific conditions, if it makes sense

**Comment by Katskan** [comment]
Just a single kit would be logistically easier and make realistic sense. Procedures that involve highly invasive placement of items come in sterile premade packs that have everything you need in them, so for example a chest tube kit has a sheet, disinfectant, gloves, scalpel, and tube often also containing a stylette and forceps. They aren't giant packages, so it would be reasonable for a backline/senior person to be carrying one or a small number, and for them to be in plenty supply on medical response vehicles. For example I have two chest tube kits at my day job. 

Also the whole hooking suction to a needle for a hemothorax doesn't really work, which is why chest tubes are over 5x the size of a decompression needle

**Comment by Will-Nichols** [comment]
Having managed a sterile reprocessing department in a hospital I can tell you from first hand experience that you can package all the items that are mentioned above into a package a little more than 10" long x 6" across and a max of 2" thick. Primarily because the sheet he mentioned is usually packaged separately and is in a fairly resilient package. The instruments can be packaged separately and usually are single use sterilization so they are all packaged separately for ease of use and they are throwaway items usually made in Pakistan, India or China. The tubing is able to be resterilized but is usually just tossed as are the gloves. Max weight would be somewhere around 6-10 ounces in total.

**Comment by Will-Nichols** [comment]
I'd be happy to help create kits for you guys. I built sterilized trauma packages for ER docs when I managed a sterile reprocessing department in a hospital. Then I traveled as a project implementation manager for sterile reprocessing for over a year to help streamline packaging and processes. So I have a fair amount of information and knowledge from the packaging side. 

When working with ER docs and quite a few of them were former combat medics from Air Force PJ to US Special Forces 18D they passed on a fair amount of information about what is really critical and how to package efficiently for best use in a trauma situation.

**Comment by FluffyGhoster** [comment]
I wonder if it's possible to work something out for advanced settings where you have to check the trachea shift and place the needle on the correct side to perform the decompression

image

**Comment by Conrimaceogain** [comment]
While a reasonable idea, I don't think I want to jump the complexity of KAT by adding that.

**Comment by Katskan** [comment]
While that is textbook, usually tracheal deviation is an extremely late sign that doesn't even happen very often

**Comment by FluffyGhoster** [comment]
> While that is textbook, usually tracheal deviation is an extremely late sign that doesn't even happen very often

I checked some sources, it seems that altought not always present it is present often (https://www.amboss.com/us/knowledge/Pneumothorax and https://radiopaedia.org/articles/tension-pneumothorax as well as the book), it is disputed if it's a sign of tension pneumothorax or not (sources seems to be in contrast) but anyways if the devs don't feel like adding that layer of complexity (even behind a setting) discussing it would be meaningless anyways

**Comment by Katskan** [comment]
A feature of tension pneumothorax that is not included right now is actually hypotension. As pressure increases in the pleural spaces you can start to see compression on the mediastinum and by extension the great vessels and heart itself, which reduces blood flow through the heart and therefore BP. Several places I've worked actually use hypotension as the basis for when to perform a decompression, if a patient does not become hypotensive a decompression is withheld until a chest tube can be placed at a hospital.

**Comment by FluffyGhoster** [comment]
> A feature of tension pneumothorax that is not included right now is actually hypotension. As pressure increases in the pleural spaces you can start to see compression on the mediastinum and by extension the great vessels and heart itself, which reduces blood flow through the heart and therefore BP. Several places I've worked actually use hypotension as the basis for when to perform a decompression, if a patient does not become hypotensive a decompression is withheld until a chest tube can be placed at a hospital.

And that can take days, that's why I think the aim for the usual lifespan of missions would be tension pneumothorax and not the plain pneumothorax

**Comment by Katskan** [comment]
> 
> 
> > A feature of tension pneumothorax that is not included right now is actually hypotension. As pressure increases in the pleural spaces you can start to see compression on the mediastinum and by extension the great vessels and heart itself, which reduces blood flow through the heart and therefore BP. Several places I've worked actually use hypotension as the basis for when to perform a decompression, if a patient does not become hypotensive a decompression is withheld until a chest tube can be placed at a hospital.
> 
> And that can take days, that's why I think the aim for the usual lifespan of missions would be tension pneumothorax and not the plain pneumothorax

What are you referring to as "that", which takes days? I've worked in rotary flight medicine for quite some time now and never seen anything from procedures or symptoms mentioned taking more than minutes- except when someone screws up their ventilator settings or fails to account for altitude pressure differentials

**Comment by FluffyGhoster** [comment]
> > > A feature of tension pneumothorax that is not included right now is actually hypotension. As pressure increases in the pleural spaces you can start to see compression on the mediastinum and by extension the great vessels and heart itself, which reduces blood flow through the heart and therefore BP. Several places I've worked actually use hypotension as the basis for when to perform a decompression, if a patient does not become hypotensive a decompression is withheld until a chest tube can be placed at a hospital.
> > 
> > 
> > And that can take days, that's why I think the aim for the usual lifespan of missions would be tension pneumothorax and not the plain pneumothorax
> 
> What are you referring to as "that", which takes days? I've worked in rotary flight medicine for quite some time now and never seen anything from procedures or symptoms mentioned taking more than minutes- except when someone screws up their ventilator settings or fails to account for altitude pressure differentials

I am referring to the normal pneumothorax, but especially the primary spontaneous pneumothorax, the pneumothoraxes that shows the most severe sympthoms are the tension ones, which can develop in trauma patients and is the most severe one

Source:
https://thorax.bmj.com/content/65/Suppl_2/ii18
"Many patients (especially those with PSP) therefore present several days after the onset of symptoms."
"Box 1 Typical clinical situations where tension pneumothorax arises:
[...]
Trauma patients."

**Pull request merged**
