### PR TITLE
Pharma | Improve | Naloxone removes ChromAberration

### PR DESCRIPTION
**Pull request by MissHeda**
**When merged this pull request will:**
- make Naloxone now remove ChromAberration when taken.

### CODE REVIEW

**Comment by MiszczuZPolski** [comment]
Only fentanyl PP effect should be delete when naloxone is taken, but if i am correct it will remove all currently active chromabberations

**Comment by AtrixZockt** [comment]
> Only fentanyl PP effect should be delete when naloxone is taken, but if i am correct it will remove all currently active chromabberations

**Comment by MissHeda** [comment]
> Only fentanyl PP effect should be delete when naloxone is taken, but if i am correct it will remove all currently active chromabberations

There is no real way to just focus the fentayl one. Either way on how you want to do it, you will always delete every other chroma as well. But TBH I don't think it will be such a big deal if you ask me.

**Comment by MiszczuZPolski** [comment]
> > Only fentanyl PP effect should be delete when naloxone is taken, but if i am correct it will remove all currently active chromabberations
> 
> There is no real way to just focus the fentayl one. Either way on how you want to do it, you will always delete every other chroma as well. But TBH I don't think it will be such a big deal if you ask me.

Not my problem, naloxone only works on opiods ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

**Comment by MissHeda** [comment]
> > > Only fentanyl PP effect should be delete when naloxone is taken, but if i am correct it will remove all currently active chromabberations
> > 
> > 
> > There is no real way to just focus the fentayl one. Either way on how you want to do it, you will always delete every other chroma as well. But TBH I don't think it will be such a big deal if you ask me.
> 
> Not my problem, naloxone only works on opiods ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

yea you are right, well then I'll have a look at what I can do, if I do not add anything soon, close the PR or I do it.

**Pull request closed without merging**
